package com.adobe.interview.blog.utils;

public class SampleData {

    public static String getSampleData(){
        return "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ut nisl a felis bibendum vestibulum. Nunc sit amet luctus metus. Aenean finibus at dolor consequat aliquam. In viverra egestas justo, non viverra erat pulvinar ut. Fusce non tellus accumsan, commodo dui id, bibendum ex. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse aliquet justo ac est sagittis luctus. Etiam non ipsum justo. Duis at dignissim sem. Integer consectetur ornare est, ac semper tellus congue quis. Aliquam nec lobortis urna, ut efficitur eros.\n" +
                "\n" +
                "Quisque viverra varius nunc. Integer facilisis orci quis nibh rutrum lacinia. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut venenatis malesuada lacus a scelerisque. Praesent posuere aliquam accumsan. Mauris ac est at augue ultrices efficitur ut non purus. Fusce laoreet mollis odio nec commodo. In ac urna ac sem pretium malesuada in at lacus. Etiam sed orci molestie, sodales lorem porttitor, semper metus. Quisque viverra ut erat quis dapibus. Nam sagittis odio ornare tempus laoreet. Nulla eu erat a orci malesuada volutpat vitae nec ligula. Donec vel posuere mauris, ac suscipit diam. Nam laoreet eu ligula nec aliquam. Nullam finibus sapien convallis, accumsan dolor et, euismod ante.\n" +
                "\n" +
                "Nullam feugiat magna vel pellentesque gravida. Morbi ante mi, elementum eu pulvinar et, pellentesque eu dolor. Proin eget ex feugiat, efficitur odio et, feugiat urna. Maecenas fringilla sapien sit amet eros tristique, eget egestas elit pharetra. Donec lobortis nunc eu nisl rutrum, sit amet volutpat nibh euismod. Integer a iaculis leo. Vivamus vel ipsum sit amet ante ullamcorper luctus. Nam porttitor nisi sit amet lectus eleifend egestas. Vestibulum eros risus, lacinia nec molestie vel, iaculis sit amet nibh. Pellentesque accumsan lobortis ex, non sodales odio mollis vel. Vestibulum vitae urna vitae diam scelerisque malesuada. Vestibulum mi nulla, aliquet iaculis velit a, cursus feugiat est. Aenean eget enim hendrerit dui molestie ultrices. Ut porttitor libero molestie quam imperdiet, eget elementum purus sagittis. Vivamus bibendum blandit diam ac mattis.\n" +
                "\n" +
                "Proin vitae sem ipsum. Maecenas nisi lectus, ullamcorper eget nisl eget, aliquam facilisis odio. Vivamus placerat libero a diam faucibus porta. Nam sit amet ligula iaculis, porttitor dolor at, euismod nisi. Quisque nec consectetur enim. Donec libero justo, suscipit non nibh varius, placerat mollis urna. Suspendisse lacinia leo quis tortor dignissim tempus. Vestibulum in sapien sagittis, malesuada lorem eu, interdum libero. Ut quis imperdiet nisl, nec suscipit lectus. Proin neque ex, iaculis et purus at, cursus pretium lorem. Proin posuere nulla in ultricies molestie. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent rhoncus risus eu metus tincidunt, vel commodo nisi sollicitudin. Curabitur vel ligula vel ligula consectetur cursus.";
    }
}
